const express = require("express");
const app = express();
const cors = require("cors");
const cookieParser = require("cookie-parser");
const customerRoutes = require("./routes/CustomerRoutes");
const shopOwnerRoutes = require("./routes/shopOwnerRoutes");
const shopProductRoutes = require("./routes/shopProductRoutes");
const cartRoutes = require("./routes/cartRoutes");
const orderRoutes = require("./routes/orderRoutes");
const captainRoutes = require("./routes/captainRoutes");
const googleMapsRoutes = require("./routes/googleMapsRoutes");
const assessmentRoutes = require("./routes/assessmentRoutes");
const notificationRoutes = require("./routes/notificationRoutes");
const adminRoutes = require("./routes/adminRoutes");

app.use(cors());
app.use(cookieParser());
app.use(express.json());
app.use("/User", customerRoutes);
app.use("/shop-owner", shopOwnerRoutes);
app.use("/", shopProductRoutes);
app.use("/", cartRoutes);
app.use("/", orderRoutes);
app.use("/captain", captainRoutes);
app.use("/maps", googleMapsRoutes);
app.use("/assessment", assessmentRoutes);
app.use("/notifications", notificationRoutes);
app.use("/admin", adminRoutes);

module.exports = app;